// src/popup/index.svelte
<script lang="ts">
    import logo from "data-base64:~assets/favicon.png";
    import Table from "./table.svelte";
    import "~style.css"
</script>

<main>
    <div class="header">
        <img src={logo} alt="Svelte Logo" style="" />
        <span>ICP Query</span>
    </div>

    <Table />
</main>

<style>
    :root {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
            Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    }

    main {
        min-width: 220px;
        text-align: center;
        padding: .5rem;
        margin: 0 auto;
    }

    .header {
        display: flex;
        flex-direction: row;
        margin: auto;
        justify-content: center;
        align-items: center;
    }

    .header span {
        margin-left: 1rem;
        color: #2ee0cf;
        text-transform: uppercase;
        font-size: 1rem;
        /* font-weight: 100; */
        /* line-height: 1.1; */
        /* margin: 2rem auto; */
        max-width: 14rem;
    }
</style>

// src/popup/index.tsx
import logo from "data-base64:~assets/favicon.png"

import Table from "./table"

import "~base.css"
import "~style.css"

export default function IndexPopup() {
  return (
    <main className="mx-auto my-0 min-w-[240px] p-4 text-center">
      <div className="m-auto flex items-center justify-center gap-4">
        <img src={logo} alt="logo" />
        <span className="max-w-[14rem] text-base uppercase text-[#2ee0cf]">
          ICP Query
        </span>
      </div>

      <Table />
    </main>
  )
}
